server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    auth_basic off;

    gzip on;
    gzip_types text/plain application/json;

    location / {
        try_files $uri $uri/ /index.html;
        autoindex on;
    }

    location ~ \.json$ {
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-cache, must-revalidate";
        expires 0;
    }

    location /dist/ {
        add_header Access-Control-Allow-Origin *;
    }
}
